kind: Job
apiVersion: batch/v1
metadata:
  name: myjob
spec:
  parallelism: 5
  template:
    metadata:
     name: testjob
    spec:
      containers:
      - name: webcont
        image: ubuntu
        command: [ "/bin/bash", "-c","echo 'Hello sumeet-singh'; sleep 10"]
      restartPolicy: Never
