kind: PersistentVolume
apiVersion: v1
metadata:
  name: myefspv01

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: fs-0fd64a2fc9b57addd.efs.eu-central-1.amazonaws.com
    path: "/"
