apiVersion: v1
kind: Pod
metadata:
  name: myprod

spec:
  containers:
    - name: c00
      image: debian
      command: ["/bin/bash", "-c", "while true; do echo 'Hello from debian container'; sleep 5; done"]
      volumeMounts:
        - name: testsecret
          mountPath: "/tmp/mysecrets"

  volumes:
    - name: testsecret
      secret:
        secretName: mysecrets
