kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    - name: webcont
      image: ubuntu
      command: [ "/bin/bash", "-c","while true; do echo Hello sumeet-singh; sleep 5; done"]
