kind: Pod
apiVersion: v1
metadata:
  name: labelpod1
  annotations:
    description: Tis pod we will define our label along with env in container
  labels:
      state-type: dev
      class: kubernetes
spec:
  containers:
    - name: resources
      image: ubuntu
      command: [ "/bin/bash", "-c", "while true; do echo 'hello from my $MYNAME '; sleep 5; done"]
      env:
        - name: MYNAME
          value: devloping
